### ISSUE TITLE
Clicking logout - does logout - but crashes the server :)

### ISSUE THREAD

**Issue by TheWoodenMan** [TheWoodenMan/twm-cpd-log#9]
with the following error:

```

C:\Users\andyn\OneDrive\Documents\GitHub\cpd-log-simple-express-app\node_modules\passport\lib\sessionmanager.js:83    
    req.session.regenerate(function(err) {
                ^

TypeError: Cannot read properties of undefined (reading 'regenerate')
    at C:\Users\andyn\OneDrive\Documents\GitHub\cpd-log-simple-express-app\node_modules\passport\lib\sessionmanager.js:83:17
    at C:\Users\andyn\OneDrive\Documents\GitHub\cpd-log-simple-express-app\node_modules\connect-mongo\build\main\lib\MongoStore.js:291:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by TheWoodenMan** [comment]
Fixed by https://github.com/TheWoodenMan/twm-cpd-log/pull/10
